interface GenreInfo {
  region: string
  flag: string
}

const GENRE_MAP: Record<string, GenreInfo> = {
  'mandopop': { region: '中国', flag: '🇨🇳' },
  'cantopop': { region: '中国香港', flag: '🇭🇰' },
  'c-pop': { region: '中国', flag: '🇨🇳' },
  'chinese': { region: '中国', flag: '🇨🇳' },
  'taiwan': { region: '中国台湾', flag: '🇹🇼' },
  'taiwan pop': { region: '中国台湾', flag: '🇹🇼' },
  'singaporean': { region: '新加坡', flag: '🇸🇬' },
  'southeast asian pop': { region: '东南亚', flag: '🌏' },
  'k-pop': { region: '韩国', flag: '🇰🇷' },
  'korean': { region: '韩国', flag: '🇰🇷' },
  'k-rap': { region: '韩国', flag: '🇰🇷' },
  'k-indie': { region: '韩国', flag: '🇰🇷' },
  'k-r&b': { region: '韩国', flag: '🇰🇷' },
  'k-ballad': { region: '韩国', flag: '🇰🇷' },
  'j-pop': { region: '日本', flag: '🇯🇵' },
  'japanese': { region: '日本', flag: '🇯🇵' },
  'j-rock': { region: '日本', flag: '🇯🇵' },
  'j-indie': { region: '日本', flag: '🇯🇵' },
  'j-rap': { region: '日本', flag: '🇯🇵' },
  'anime': { region: '日本', flag: '🇯🇵' },
  'anison': { region: '日本', flag: '🇯🇵' },
  'vocaloid': { region: '日本', flag: '🇯🇵' },
  'pop': { region: '全球', flag: '🌍' },
  'indie/alternative': { region: '全球', flag: '🌍' },
  'singer-songwriter': { region: '全球', flag: '🌍' },
  'singer-songwriter/folk': { region: '全球', flag: '🌍' },
  'dance pop': { region: '全球', flag: '🌍' },
  'art pop': { region: '全球', flag: '🌍' },
  'synth-pop': { region: '全球', flag: '🌍' },
  'electropop': { region: '全球', flag: '🌍' },
  'dream pop': { region: '全球', flag: '🌍' },
  'chamber pop': { region: '全球', flag: '🌍' },
  'bedroom pop': { region: '全球', flag: '🌍' },
  'alt-pop': { region: '全球', flag: '🌍' },
  'hyperpop': { region: '全球', flag: '🌍' },
  'rock': { region: '全球', flag: '🌍' },
  'rock/alternative': { region: '全球', flag: '🌍' },
  'classic rock': { region: '全球', flag: '🌍' },
  'hard rock': { region: '全球', flag: '🌍' },
  'soft rock': { region: '全球', flag: '🌍' },
  'pop rock': { region: '全球', flag: '🌍' },
  'indie rock': { region: '全球', flag: '🌍' },
  'alt-rock': { region: '全球', flag: '🌍' },
  'psychedelic rock': { region: '全球', flag: '🌍' },
  'garage rock': { region: '全球', flag: '🌍' },
  'post-rock': { region: '全球', flag: '🌍' },
  'hip hop': { region: '美国', flag: '🇺🇸' },
  'hip hop/rap': { region: '美国', flag: '🇺🇸' },
  'rap': { region: '美国', flag: '🇺🇸' },
  'trap': { region: '美国', flag: '🇺🇸' },
  'drill': { region: '美国', flag: '🇺🇸' },
  'boom bap': { region: '美国', flag: '🇺🇸' },
  'conscious hip hop': { region: '美国', flag: '🇺🇸' },
  'gangsta rap': { region: '美国', flag: '🇺🇸' },
  'southern hip hop': { region: '美国', flag: '🇺🇸' },
  'east coast hip hop': { region: '美国', flag: '🇺🇸' },
  'west coast hip hop': { region: '美国', flag: '🇺🇸' },
  'r&b': { region: '美国', flag: '🇺🇸' },
  'r&b/soul': { region: '美国', flag: '🇺🇸' },
  'contemporary r&b': { region: '美国', flag: '🇺🇸' },
  'neo soul': { region: '美国', flag: '🇺🇸' },
  'alternative r&b': { region: '美国', flag: '🇺🇸' },
  'edm': { region: '全球', flag: '🌍' },
  'electronic/dance': { region: '全球', flag: '🌍' },
  'electronic': { region: '全球', flag: '🌍' },
  'house': { region: '全球', flag: '🌍' },
  'deep house': { region: '全球', flag: '🌍' },
  'techno': { region: '全球', flag: '🌍' },
  'trance': { region: '全球', flag: '🌍' },
  'dubstep': { region: '全球', flag: '🌍' },
  'ambient': { region: '全球', flag: '🌍' },
  'downtempo': { region: '全球', flag: '🌍' },
  'idm': { region: '全球', flag: '🌍' },
  'latin': { region: '拉美', flag: '🌎' },
  'reggaeton': { region: '拉美', flag: '🌎' },
  'latin pop': { region: '拉美', flag: '🌎' },
  'latin rock': { region: '拉美', flag: '🌎' },
  'latin hip hop': { region: '拉美', flag: '🌎' },
  'salsa': { region: '拉美', flag: '🌎' },
  'bachata': { region: '拉美', flag: '🌎' },
  'dembow': { region: '拉美', flag: '🌎' },
  'bossa nova': { region: '巴西', flag: '🇧🇷' },
  'samba': { region: '巴西', flag: '🇧🇷' },
  'mpb': { region: '巴西', flag: '🇧🇷' },
  'indie': { region: '全球', flag: '🌍' },
  'indie pop': { region: '全球', flag: '🌍' },
  'indie folk': { region: '全球', flag: '🌍' },
  'indie soul': { region: '全球', flag: '🌍' },
  'folk': { region: '全球', flag: '🌍' },
  'traditional/folk': { region: '全球', flag: '🌍' },
  'folk rock': { region: '全球', flag: '🌍' },
  'neo-folk': { region: '全球', flag: '🌍' },
  'classical': { region: '全球', flag: '🎼' },
  'classical/instrumental': { region: '全球', flag: '🎼' },
  'orchestral': { region: '全球', flag: '🎼' },
  'opera': { region: '全球', flag: '🎼' },
  'baroque': { region: '全球', flag: '🎼' },
  'instrumental': { region: '全球', flag: '🎼' },
  'lo-fi': { region: '全球', flag: '🎼' },
  'post-rock instrumental': { region: '全球', flag: '🎼' },
  'jazz': { region: '美国', flag: '🇺🇸' },
  'jazz/blues': { region: '美国', flag: '🇺🇸' },
  'bebop': { region: '美国', flag: '🇺🇸' },
  'cool jazz': { region: '美国', flag: '🇺🇸' },
  'fusion': { region: '美国', flag: '🇺🇸' },
  'smooth jazz': { region: '美国', flag: '🇺🇸' },
  'acid jazz': { region: '美国', flag: '🇺🇸' },
  'soul': { region: '美国', flag: '🇺🇸' },
  'funk': { region: '美国', flag: '🇺🇸' },
  'motown': { region: '美国', flag: '🇺🇸' },
  'disco': { region: '美国', flag: '🇺🇸' },
  'country': { region: '美国', flag: '🇺🇸' },
  'country/americana': { region: '美国', flag: '🇺🇸' },
  'country pop': { region: '美国', flag: '🇺🇸' },
  'country rock': { region: '美国', flag: '🇺🇸' },
  'outlaw country': { region: '美国', flag: '🇺🇸' },
  'alt-country': { region: '美国', flag: '🇺🇸' },
  'americana/roots': { region: '美国', flag: '🇺🇸' },
  'americana': { region: '美国', flag: '🇺🇸' },
  'bluegrass': { region: '美国', flag: '🇺🇸' },
  'metal': { region: '全球', flag: '🌍' },
  'heavy metal': { region: '全球', flag: '🌍' },
  'death metal': { region: '全球', flag: '🌍' },
  'black metal': { region: '全球', flag: '🌍' },
  'thrash metal': { region: '全球', flag: '🌍' },
  'power metal': { region: '全球', flag: '🌍' },
  'doom metal': { region: '全球', flag: '🌍' },
  'progressive metal': { region: '全球', flag: '🌍' },
  'nu metal': { region: '全球', flag: '🌍' },
  'metalcore': { region: '全球', flag: '🌍' },
  'punk': { region: '全球', flag: '🌍' },
  'pop punk': { region: '全球', flag: '🌍' },
  'hardcore punk': { region: '全球', flag: '🌍' },
  'emo': { region: '全球', flag: '🌍' },
  'post-punk': { region: '全球', flag: '🌍' },
  'alternative': { region: '全球', flag: '🌍' },
  'grunge': { region: '美国', flag: '🇺🇸' },
  'shoegaze': { region: '全球', flag: '🌍' },
  'new wave': { region: '全球', flag: '🌍' },
  'post-punk revival': { region: '全球', flag: '🌍' },
  'britpop': { region: '英国', flag: '🇬🇧' },
  'uk garage': { region: '英国', flag: '🇬🇧' },
  'grime': { region: '英国', flag: '🇬🇧' },
  'drum and bass': { region: '英国', flag: '🇬🇧' },
  'dub': { region: '英国', flag: '🇬🇧' },
  'reggae': { region: '牙买加', flag: '🇯🇲' },
  'dancehall': { region: '牙买加', flag: '🇯🇲' },
  'ska': { region: '牙买加', flag: '🇯🇲' },
  'afrobeats': { region: '非洲', flag: '🌍' },
  'afrobeats/afropop': { region: '非洲', flag: '🌍' },
  'afrobeat': { region: '非洲', flag: '🌍' },
  'afropop': { region: '非洲', flag: '🌍' },
  'highlife': { region: '非洲', flag: '🌍' },
  'gospel': { region: '美国', flag: '🇺🇸' },
  'christian': { region: '全球', flag: '🌍' },
  'worship': { region: '全球', flag: '🌍' },
  'gospel/christian': { region: '全球', flag: '🌍' },
  'holiday': { region: '全球', flag: '🌍' },
  'soundtrack/stage': { region: '全球', flag: '🌍' },
  'children/family': { region: '全球', flag: '🌍' },
  'comedy/spoken': { region: '全球', flag: '🌍' },
  'caribbean': { region: '加勒比', flag: '🌎' },
  'brazilian': { region: '巴西', flag: '🇧🇷' },
  'blues': { region: '美国', flag: '🇺🇸' },
  'delta blues': { region: '美国', flag: '🇺🇸' },
  'chicago blues': { region: '美国', flag: '🇺🇸' },
  'french': { region: '法国', flag: '🇫🇷' },
  'chanson': { region: '法国', flag: '🇫🇷' },
  'french pop': { region: '法国', flag: '🇫🇷' },
  'german': { region: '德国', flag: '🇩🇪' },
  'schlager': { region: '德国', flag: '🇩🇪' },
  'italian': { region: '意大利', flag: '🇮🇹' },
  'italo disco': { region: '意大利', flag: '🇮🇹' },
  'spanish': { region: '西班牙', flag: '🇪🇸' },
  'flamenco': { region: '西班牙', flag: '🇪🇸' },
  'indian': { region: '印度', flag: '🇮🇳' },
  'bollywood': { region: '印度', flag: '🇮🇳' },
  'bhangra': { region: '印度', flag: '🇮🇳' },
  'carnatic': { region: '印度', flag: '🇮🇳' },
  'arabic': { region: '中东', flag: '🌍' },
  'rai': { region: '中东', flag: '🌍' },
  'turkish': { region: '土耳其', flag: '🇹🇷' },
  'nordic': { region: '北欧', flag: '🌍' },
  'swedish': { region: '瑞典', flag: '🇸🇪' },
  'russian': { region: '俄罗斯', flag: '🇷🇺' },
  'world': { region: '全球', flag: '🌍' },
  'world fusion': { region: '全球', flag: '🌍' },
}

const UNKNOWN_INFO: GenreInfo = { region: '未知', flag: '🌍' }

export function classifyGenre(genre: string): GenreInfo {
  const key = genre.toLowerCase().trim()
  return GENRE_MAP[key] ?? UNKNOWN_INFO
}

export function inferRegionDist(genres: { name: string; play_share: number }[]): { region: string; flag: string; play_share: number }[] {
  const agg: Record<string, { region: string; flag: string; play_share: number }> = {}

  for (const g of genres) {
    const info = classifyGenre(g.name)
    const key = info.region
    if (!agg[key]) {
      agg[key] = { region: info.region, flag: info.flag, play_share: 0 }
    }
    agg[key].play_share += g.play_share
  }

  return Object.values(agg).sort((a, b) => b.play_share - a.play_share)
}
